# Generated by Django 4.0.4 on 2023-09-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api_logger', '0002_auto_20211221_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilogsmodel',
            name='user_id',
            field=models.TextField(default=''),
        ),
    ]
