# Generated by Django 4.0.4 on 2023-09-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='about',
        ),
        migrations.AddField(
            model_name='newuser',
            name='described',
            field=models.TextField(blank=True, max_length=500, verbose_name='described'),
        ),
    ]
