# Generated by Django 4.0.4 on 2023-10-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_newuser_described_newuser_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='division',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
