# Generated by Django 4.0.4 on 2023-10-16 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_newuser_created_at_newuser_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupExpended',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.group')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
