include:
  - project: 'ETC/devops/cicd-templates'
    file: 'deploy-to-eks.yml'
  - project: 'ETC/devops/cicd-templates'
    file: 'deploy-to-on-prem.yml'
  - project: 'ETC/devops/cicd-templates'
    file: 'docker-build.yml'
  - project: 'ETC/devops/cicd-templates'
    file: 'semantic-versioning.yml'

#  - project: 'ETC/devops/cicd-templates'
#    file: 'migration.yml'
#  - project: 'ETC/devops/cicd-templates'
#    file: 'test-coverage.yml'
#  - project: 'ETC/devops/cicd-templates'
#    file: 'security.yml'
#  - project: 'ETC/devops/cicd-templates'
#    file: 'generate-reports.yml'

variables:
  APP_NAME: aurora
  NAMESPACE: arbeon-utils
  ECR_REPO_URL: 873799242473.dkr.ecr.ap-northeast-2.amazonaws.com
  ECR_TOKEN: secret-password
  OTEL_EXPORTER_ENDPOINT: "otel-collector.otel-system.svc.cluster.local:4317"
  SERVICE_PORT: 8000

  # postgresql
  DATABASE_NAME: "aurora"
  DATABASE_USER: "postgres"
  DATABASE_PORT: "5432"

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /feature/
      variables:
        # POSTGRESQL
        DATABASE_HOST: "192.168.51.92"
        DATABASE_PASSWORD: "${DB_PG_PW}"
    - if: $CI_COMMIT_BRANCH == "develop"
      variables:
        ENV: "dev"
        SERVICE_TYPE: "ClusterIP"
        KUBE_CONFIG: ${DEV_KUBE_CONFIG}
        # POSTGRESQL
        DATABASE_HOST: "192.168.51.92"
        DATABASE_PASSWORD: "${DB_PG_PW}"
        # INGRESS
        CERT_DNS: "*.arbeon.com"
        INGRESS_HOST: "aurora-dev.arbeon.com"
    - if: $CI_COMMIT_BRANCH == "integration"
      variables:
        ENV: "inte"
        SERVICE_TYPE: "ClusterIP"
        KUBE_CONFIG: ${INTE_KUBE_CONFIG}
        # POSTGRESQL
        DATABASE_HOST: "192.168.51.92"
        DATABASE_PASSWORD: "${DB_PG_PW}"
        # INGRESS
        CERT_DNS: "*.arbeon.com"
        INGRESS_HOST: "aurora-dev.arbeon.com"
    - if: $CI_COMMIT_BRANCH == "staging"
      variables:
        ENV: "staging"
        EKS_CLUSTER_NAME: "arbeon-staging-cls"
        SERVICE_TYPE: "NodePort"
        # POSTGRESQL
        DATABASE_HOST: "arbeon-staging-db-cls.cluster-czqqo2sfzzru.ap-northeast-2.rds.amazonaws.com"
        DATABASE_PASSWORD: "${AWS_PG_PW}"
        # INGRESS
        ALB_NAME: "aurora-alb"
        ALB_SCHEME: "internet-facing"
        # "*.arbeon.com" cert-arn
        ALB_CERT_ARN: "arn:aws:acm:ap-northeast-2:873799242473:certificate/9f247e95-7e34-4921-b07d-90fe76924a44"
        INGRESS_HOST: "aurora-staging.arbeon.com"
    - if: $CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "web"
      variables:
        ENV: "production"
        EKS_CLUSTER_NAME: "arbeon-production-cls"
        SERVICE_TYPE: "NodePort"
        # INGRESS
        ALB_NAME: "aurora-alb"
        ALB_SCHEME: "internet-facing"
        # "*.arbeon.com" cert-arn
        ALB_CERT_ARN: "arn:aws:acm:ap-northeast-2:873799242473:certificate/9f247e95-7e34-4921-b07d-90fe76924a44"
        INGRESS_HOST: "aurora-staging.arbeon.com"
        # POSTGRESQL
        DATABASE_HOST: "arbeon-production-db-cls.cluster-czqqo2sfzzru.ap-northeast-2.rds.amazonaws.com"
        DATABASE_PASSWORD: "${AWS_PG_PW}"

stages:
  - semantic-versioning
  - build
  - deploy