# Generated by Django 4.0.4 on 2023-10-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FlywaySchemaHistory',
            fields=[
                ('installed_rank', models.IntegerField(primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=20)),
                ('script', models.CharField(max_length=1000)),
                ('checksum', models.IntegerField(blank=True, null=True)),
                ('installed_by', models.CharField(max_length=100)),
                ('installed_on', models.DateTimeField()),
                ('execution_time', models.IntegerField()),
                ('success', models.BooleanField()),
            ],
            options={
                'db_table': 'flyway_schema_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('goods_name', models.CharField(blank=True, max_length=255, null=True)),
                ('goods_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('goods_img', models.CharField(blank=True, max_length=255, null=True)),
                ('goods_price', models.IntegerField(blank=True, null=True)),
                ('goods_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('goods_category', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('mg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('discount_flag', models.BooleanField(blank=True, null=True)),
                ('ci_logo', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_category', models.CharField(blank=True, max_length=255, null=True)),
                ('small_category', models.CharField(blank=True, max_length=255, null=True)),
                ('relation_goods', models.JSONField(blank=True, null=True)),
                ('sku', models.IntegerField(blank=True, null=True)),
                ('media_list', models.JSONField(blank=True, null=True)),
                ('brand_color', models.CharField(blank=True, max_length=255, null=True)),
                ('goods_price_str', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_price_str', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsProductRelation',
            fields=[
                ('gpr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('goods_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'goods_product_relation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImageRecognition',
            fields=[
                ('mg_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_scan_id', models.CharField(blank=True, max_length=255, null=True)),
                ('first_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('add_info', models.JSONField(blank=True, null=True)),
                ('like_cnt', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'image_recognition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScanInfo',
            fields=[
                ('scan_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('mg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('crop_img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('geohash', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status_flag', models.SmallIntegerField(blank=True, null=True)),
                ('img_name', models.CharField(blank=True, max_length=255, null=True)),
                ('enc_geo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'scan_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScanLike',
            fields=[
                ('sl_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('scan_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scan_like',
                'managed': False,
            },
        ),
    ]
