# Generated by Django 4.0.4 on 2023-10-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('block_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('blocked_user_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'block',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('follow_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('target_id', models.UUIDField()),
                ('created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'follow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('reported_user_id', models.UUIDField()),
                ('report_reason', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('account_id', models.UUIDField()),
                ('email', models.CharField(max_length=255)),
                ('user_tag', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_img', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_msg', models.CharField(blank=True, max_length=255, null=True)),
                ('user_tag_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('following_cnt', models.IntegerField()),
                ('follower_cnt', models.IntegerField()),
                ('f4f_cnt', models.IntegerField()),
                ('creator_level', models.IntegerField()),
                ('agree_promotion_terms_at', models.DateTimeField(blank=True, null=True)),
                ('app_version', models.CharField(blank=True, max_length=255, null=True)),
                ('device_lang', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(blank=True, max_length=255, null=True)),
                ('os_type', models.CharField(blank=True, max_length=255, null=True)),
                ('os_version', models.CharField(blank=True, max_length=255, null=True)),
                ('player_id', models.CharField(blank=True, max_length=255, null=True)),
                ('push_token', models.CharField(blank=True, max_length=255, null=True)),
                ('udid', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTagPool',
            fields=[
                ('user_tag_pool_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_tag', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_tag_pool',
                'managed': False,
            },
        ),
    ]
