# Generated by Django 4.0.4 on 2023-10-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_content_contentlike_contentlikerelation_contentreply_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.UUIDField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('birth', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField()),
                ('changed_password_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthCheck',
            fields=[
                ('auth_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('auth_info', models.CharField(max_length=255)),
                ('auth_type', models.CharField(max_length=255)),
                ('auth_status', models.SmallIntegerField()),
                ('account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('authenticated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_check',
                'managed': False,
            },
        ),
    ]
