# Generated by Django 4.0.4 on 2023-09-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryScanInfo',
            fields=[
                ('scan_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reg_date', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryUserInfo',
            fields=[
                ('summary_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
