# Generated by Django 4.0.4 on 2023-09-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryScanInfo',
            fields=[
                ('scan_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reg_date', models.CharField(max_length=255)),
                ('scan_success', models.BigIntegerField(default=0)),
                ('scan_fail', models.BigIntegerField(default=0)),
                ('scan_user', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'summary_scan_info',
            },
        ),
        migrations.CreateModel(
            name='SummaryUserInfo',
            fields=[
                ('summary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('summary_dt', models.CharField(max_length=255)),
                ('total_user', models.BigIntegerField(default=0)),
                ('new_user', models.BigIntegerField(default=0)),
                ('suspended_user', models.BigIntegerField(default=0)),
                ('deleted_user', models.BigIntegerField(default=0)),
                ('return_user', models.BigIntegerField(default=0)),
                ('inactive_user', models.BigIntegerField(default=0)),
                ('dau', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'summary_user_info',
            },
        ),
    ]
