# Generated by Django 4.0.4 on 2023-09-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0006_summaryscandailyinfo_summaryscanhourinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryUserHourInfo',
            fields=[
                ('summary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('summary_dt', models.CharField(blank=True, max_length=255, verbose_name='통계일자')),
                ('total_user', models.BigIntegerField(blank=True, default=0)),
                ('new_user', models.BigIntegerField(blank=True, default=0)),
                ('suspended_user', models.BigIntegerField(blank=True, default=0)),
                ('deleted_user', models.BigIntegerField(blank=True, default=0)),
                ('return_user', models.BigIntegerField(blank=True, default=0)),
                ('inactive_user', models.BigIntegerField(blank=True, default=0)),
                ('dau', models.BigIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'summary_user_hour_info',
            },
        ),
    ]
