# Generated by Django 4.0.4 on 2023-10-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0007_summaryuserhourinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryUserPeriodInfo',
            fields=[
                ('summary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('summary_dt', models.CharField(max_length=255, unique=True)),
                ('use_day_7', models.BigIntegerField(blank=True, default=0)),
                ('use_day_30', models.BigIntegerField(blank=True, default=0)),
                ('use_day_60', models.BigIntegerField(blank=True, default=0)),
                ('use_day_90', models.BigIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'summary_user_period_info',
                'managed': False,
            },
        ),
    ]
