# Generated by Django 4.0.4 on 2023-10-11 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0008_summaryuserperiodinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summaryuserperiodinfo',
            options={},
        ),
    ]
