# Generated by Django 4.0.4 on 2023-10-12 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0009_alter_summaryuserperiodinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summaryuserperiodinfo',
            options={'managed': True},
        ),
    ]
