# Generated by Django 4.0.4 on 2023-10-12 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0010_alter_summaryscanhourinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summaryscanhourinfo',
            options={},
        ),
    ]
