# Generated by Django 4.0.4 on 2023-10-12 07:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aurora", "0012_summaryuserperiodinfo_delete_summaryuserterminfo"),
    ]

    operations = []
