# Generated by Django 4.0.4 on 2023-10-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0014_alter_summaryscandailyinfo_scan_fail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryscanhourinfo',
            name='summary_hour',
            field=models.CharField(blank=True, max_length=255, verbose_name='통계시간'),
        ),
        migrations.AlterUniqueTogether(
            name='summaryscanhourinfo',
            unique_together={('summary_dt', 'summary_id')},
        ),
    ]
