# Generated by Django 4.0.4 on 2023-10-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0015_summaryscanhourinfo_summary_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryscanmonthinfo',
            name='scan_fail',
            field=models.BigIntegerField(default=0, verbose_name='스캔실패'),
        ),
        migrations.AlterField(
            model_name='summaryscanmonthinfo',
            name='scan_success',
            field=models.BigIntegerField(default=0, verbose_name='스캔성공'),
        ),
        migrations.AlterField(
            model_name='summaryscanmonthinfo',
            name='summary_dt',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='통계일자'),
        ),
        migrations.AlterField(
            model_name='summaryscanmonthinfo',
            name='total_scan_user',
            field=models.BigIntegerField(default=0, verbose_name='스캔참여회원'),
        ),
    ]
