# Generated by Django 4.0.4 on 2023-10-12 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0016_alter_summaryscanmonthinfo_scan_fail_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='summaryscanhourinfo',
            unique_together={('summary_dt', 'summary_hour')},
        ),
    ]
