# Generated by Django 4.0.4 on 2023-10-13 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0011_alter_summaryscanhourinfo_options'),
        ('aurora', '0017_alter_summaryscanhourinfo_unique_together'),
    ]

    operations = [
    ]
