# Generated by Django 4.0.4 on 2023-10-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0018_merge_20231013_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArscanRelation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_id', models.CharField(max_length=255)),
                ('target_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'arscan_relation',
            },
        ),
    ]
