# Generated by Django 4.0.4 on 2023-10-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0019_arscanrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='arscanrelation',
            name='source_label',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='arscanrelation',
            name='target_label',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
