# Generated by Django 4.0.4 on 2023-10-19 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0020_arscanrelation_source_label_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArscanRelation',
        ),
    ]
