# Generated by Django 4.0.4 on 2023-10-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0021_delete_arscanrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='카테고리 고유값')),
                ('parent_id', models.IntegerField(default=0, verbose_name='상위 카테고리 고유값')),
                ('content_type', models.IntegerField(default=0, verbose_name='퍼미션 타입')),
                ('category_name', models.CharField(max_length=255, verbose_name='카테고리 코드')),
                ('category_desc', models.CharField(max_length=255, verbose_name='카테고리 설명')),
                ('uri', models.CharField(blank=True, max_length=255, verbose_name='카테고리 URI')),
                ('order', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
