# Generated by Django 4.0.4 on 2023-10-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0022_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryuserdailyinfo',
            name='new_dau',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summaryusermonthinfo',
            name='new_dau',
            field=models.BigIntegerField(default=0),
        ),
    ]
