# Generated by Django 4.0.4 on 2023-10-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0023_summaryuserdailyinfo_new_dau_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryuserdailyinfo',
            name='summary_dt',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='통계일자'),
        ),
        migrations.AlterField(
            model_name='summaryusermonthinfo',
            name='summary_dt',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='통계일자'),
        ),
    ]
