# Generated by Django 4.0.4 on 2023-10-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0024_alter_summaryuserdailyinfo_summary_dt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryContentDailyInfo',
            fields=[
                ('summary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('summary_dt', models.CharField(max_length=255, unique=True)),
                ('post_cnt', models.BigIntegerField(default=0)),
                ('post_user_cnt', models.BigIntegerField(default=0)),
                ('media_cnt', models.BigIntegerField(default=0)),
                ('media_user_cnt', models.BigIntegerField(default=0)),
                ('arbecon_cnt', models.BigIntegerField(default=0)),
                ('arbecon_user_cnt', models.BigIntegerField(default=0)),
                ('drawing_cnt', models.BigIntegerField(default=0)),
                ('drawing_user_cnt', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'summary_content_daily_info',
            },
        ),
        migrations.CreateModel(
            name='SummaryContentMonthInfo',
            fields=[
                ('summary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('summary_dt', models.CharField(max_length=255, unique=True)),
                ('post_cnt', models.BigIntegerField(default=0)),
                ('post_user_cnt', models.BigIntegerField(default=0)),
                ('media_cnt', models.BigIntegerField(default=0)),
                ('media_user_cnt', models.BigIntegerField(default=0)),
                ('arbecon_cnt', models.BigIntegerField(default=0)),
                ('arbecon_user_cnt', models.BigIntegerField(default=0)),
                ('drawing_cnt', models.BigIntegerField(default=0)),
                ('drawing_user_cnt', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'summary_content_month_info',
            },
        ),
    ]
