# Generated by Django 4.0.4 on 2023-10-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0025_summarycontentdailyinfo_summarycontentmonthinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbeconResource',
            fields=[
                ('resource_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('motion_name', models.CharField(max_length=255)),
                ('show_name', models.CharField(max_length=255)),
                ('resource_desc', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryMediaMonthInfo',
            fields=[
                ('summary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('summary_dt', models.CharField(max_length=255)),
                ('content_type', models.SmallIntegerField(default=0)),
                ('content_cnt', models.BigIntegerField(default=0)),
                ('content_user_cnt', models.BigIntegerField(default=0)),
                ('like_cnt', models.BigIntegerField(default=0)),
                ('like_user_cnt', models.BigIntegerField(default=0)),
                ('up_cnt', models.BigIntegerField(default=0)),
                ('up_user_cnt', models.BigIntegerField(default=0)),
                ('reply_cnt', models.BigIntegerField(default=0)),
                ('reply_user_cnt', models.BigIntegerField(default=0)),
                ('share_cnt', models.BigIntegerField(default=0)),
                ('share_user_cnt', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'summary_media_month_info',
                'unique_together': {('summary_dt', 'content_type')},
            },
        ),
        migrations.CreateModel(
            name='SummaryMediaDailyInfo',
            fields=[
                ('summary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('summary_dt', models.CharField(max_length=255)),
                ('content_type', models.SmallIntegerField(default=0)),
                ('content_cnt', models.BigIntegerField(default=0)),
                ('content_user_cnt', models.BigIntegerField(default=0)),
                ('like_cnt', models.BigIntegerField(default=0)),
                ('like_user_cnt', models.BigIntegerField(default=0)),
                ('up_cnt', models.BigIntegerField(default=0)),
                ('up_user_cnt', models.BigIntegerField(default=0)),
                ('reply_cnt', models.BigIntegerField(default=0)),
                ('reply_user_cnt', models.BigIntegerField(default=0)),
                ('share_cnt', models.BigIntegerField(default=0)),
                ('share_user_cnt', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'summary_media_daily_info',
                'unique_together': {('summary_dt', 'content_type')},
            },
        ),
        migrations.CreateModel(
            name='SummaryDrawingMonthInfo',
            fields=[
                ('summary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('summary_dt', models.CharField(max_length=255)),
                ('drawing_type', models.SmallIntegerField(default=0)),
                ('content_cnt', models.BigIntegerField(default=0)),
                ('content_user_cnt', models.BigIntegerField(default=0)),
                ('like_cnt', models.BigIntegerField(default=0)),
                ('like_user_cnt', models.BigIntegerField(default=0)),
                ('share_cnt', models.BigIntegerField(default=0)),
                ('share_user_cnt', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'summary_drawing_month_info',
                'unique_together': {('summary_dt', 'drawing_type')},
            },
        ),
        migrations.CreateModel(
            name='SummaryDrawingDailyInfo',
            fields=[
                ('summary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('summary_dt', models.CharField(max_length=255)),
                ('drawing_type', models.SmallIntegerField(default=0)),
                ('content_cnt', models.BigIntegerField(default=0)),
                ('content_user_cnt', models.BigIntegerField(default=0)),
                ('like_cnt', models.BigIntegerField(default=0)),
                ('like_user_cnt', models.BigIntegerField(default=0)),
                ('share_cnt', models.BigIntegerField(default=0)),
                ('share_user_cnt', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'summary_drawing_daily_info',
                'unique_together': {('summary_dt', 'drawing_type')},
            },
        ),
        migrations.CreateModel(
            name='SummaryArbeconMonthInfo',
            fields=[
                ('summary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('summary_dt', models.CharField(max_length=255)),
                ('resource_id', models.CharField(max_length=255)),
                ('content_cnt', models.BigIntegerField(default=0)),
                ('content_user_cnt', models.BigIntegerField(default=0)),
                ('like_cnt', models.BigIntegerField(default=0)),
                ('like_user_cnt', models.BigIntegerField(default=0)),
                ('share_cnt', models.BigIntegerField(default=0)),
                ('share_user_cnt', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'summary_arbecon_month_info',
                'unique_together': {('summary_dt', 'resource_id')},
            },
        ),
        migrations.CreateModel(
            name='SummaryArbeconDailyInfo',
            fields=[
                ('summary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('summary_dt', models.CharField(max_length=255)),
                ('resource_id', models.CharField(max_length=255)),
                ('content_cnt', models.BigIntegerField(default=0)),
                ('content_user_cnt', models.BigIntegerField(default=0)),
                ('like_cnt', models.BigIntegerField(default=0)),
                ('like_user_cnt', models.BigIntegerField(default=0)),
                ('share_cnt', models.BigIntegerField(default=0)),
                ('share_user_cnt', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'summary_arbecon_daily_info',
                'unique_together': {('summary_dt', 'resource_id')},
            },
        ),
    ]
