# Generated by Django 4.0.4 on 2023-10-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0026_arbeconresource_summarymediamonthinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarydrawingdailyinfo',
            name='drawing_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='summarydrawingmonthinfo',
            name='drawing_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='summarymediadailyinfo',
            name='content_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='summarymediamonthinfo',
            name='content_type',
            field=models.CharField(max_length=255),
        ),
    ]
