apiVersion: v1
kind: Secret
metadata:
  name: ecr-secret
  namespace: {{ .Values.namespace }}
  annotations:
    # #secret 삭제 방지
    # "helm.sh/resource-policy": "keep"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
